---
- name: check mac and product uuid
  hosts: all
  become: yes
  become_method: sudo
  remote_user: k8stall
  tasks:
    - name: get product uuid
      shell: cat /sys/class/dmi/id/product_uuid
      register: product_uuid

    - name: print product uuid
      debug:
        msg: product uuid {{ product_uuid.stdout }}
