---
- name: copy containerd configuration file
  hosts: nfs_server
  become: yes
  become_method: sudo
  remote_user: k8stall
  tasks:
    - name: copy containerd configuration file
      copy:
        src: files/nfs-server/etc/exports
        dest: /etc/exports
        mode: preserve
        owner: root
        group: root

    - name: create nfs share directory
      shell: mkdir -p /nfs/k8s

    - name: apply exports
      shell: exportfs -a
