---
- name: Copy /etc/hosts
  hosts: all
  become: yes
  become_method: sudo
  remote_user: k8stall
  tasks:
    - name: copy /etc/hosts
      copy:
        src: files/common/etc/hosts
        dest: /etc/hosts
        mode: 0644
        owner: root
        group: root

