---
- name: install containerd
  hosts: k8s
  become: yes
  become_method: sudo
  remote_user: k8stall
  tasks:
    - name: install containerd
      apt: 
        name: containerd
        state: present

    - name: restart containerd 
      service:
        name: containerd
        state: restarted
