apiVersion: v1
kind: Service
metadata:
  name: hello-flask
  namespace: hello-flask
spec:
  selector:
    app: hello-flask
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
