apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-flask
  namespace: hello-flask
spec:
  selector:
    matchLabels:
      app: hello-flask
  replicas: 4
  template:
    metadata:
      labels:
        app: hello-flask
    spec:
      containers:
      - name: hello-flask
        image: registry.local/hello-flask:v0.0.3
        imagePullPolicy: Always
        ports:
        - containerPort: 80

