apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: bbs
  labels:
    app: web
    tier: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
        tier: frontend
    spec:
      containers:
      - name: web
        image: registry.local/bbs:v0.0.1
        ports:
        - containerPort: 80
