apiVersion: v1
kind: Service
metadata:
  name: web
  namespace: bbs
  labels:
    app: web
    tier: frontend
spec:
  type: NodePort
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
  selector:
    app: web
    tier: frontend
