---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: busybox-sfs
spec:
  serviceName: busybox
  replicas: 2
  selector:
    matchLabels:
      app: busybox
  template:
    metadata:
      labels:
        app: busybox
    spec:
      containers:
      - name: busybox
        image: registry.local/busybox:latest
        command: ['sh', '-c', 'sleep 3000']
        ports:
        - containerPort: 80
          name: web
        volumeMounts:
        - name: mnt
          mountPath: /mnt
  volumeClaimTemplates:
  - metadata:
      name: mnt
    spec:
      storageClassName: nfs-client
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 10Mi
---
apiVersion: v1
kind: Service
metadata:
  name: busybox
  labels:
    app: busybox
spec:
  ports:
  - port: 80
    name: web
  clusterIP: None
  selector:
    app: busybox
