apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: busybox-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi
  storageClassName: local-storage
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: busybox-storage
  labels:
    app: busybox-storage
spec:
  selector:
    matchLabels:
      app: busybox-storage
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: busybox-storage
    spec:
      containers:
      - image: registry.local/busybox:latest
        name: busybox-storage
        command: ['sh', '-c', 'sleep 3000']
        volumeMounts:
        - name: busybox-pv
          mountPath: /mnt
      volumes:
      - name: busybox-pv
        persistentVolumeClaim:
          claimName: busybox-pvc
